
export const ADD_TOPPING = 'ADD_TOPPING';
export const REMOVE_TOPPING = 'REMOVE_TOPPING';
export const CLEAR_TOPPING = 'CLEAR_TOPPING';
export const SET_TOPPINGS = 'SET_TOPPINGS';

export const COMPILE_TOPPINGS = 'COMPILE_TOPPINGS';
export const UPDATE_PRICE = 'UPDATE_PRICE';
export const UPDATE_TOPPINGS = 'UPDATE_TOPPINGS';